package android;

import heranca.CadastroPessoa;
import heranca.Pesquisa;
import heranca.Pessoa;
import heranca.PessoaFisica;
import heranca.PessoaJuridica;
import javax.swing.JOptionPane;

/**
 *
 * @author Emerson Santos
 */
public class Cadastro extends javax.swing.JFrame {

    CadastroPessoa conttroller;
    Pessoa pessoa = null;
    int posicao = -1;
    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
        conttroller = new CadastroPessoa(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupRadio = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblTipoPessoa = new javax.swing.JLabel();
        radioPF = new javax.swing.JRadioButton();
        radioPJ = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        lblMensagem = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        frameDadosComuns = new javax.swing.JInternalFrame();
        lblNome = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        frameDadosEspecificos = new javax.swing.JInternalFrame();
        lblRGIE = new javax.swing.JLabel();
        lblCpfCnpj = new javax.swing.JLabel();
        txtRGIE = new javax.swing.JTextField();
        txtCpfCnpj = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("CADASTRO");

        lblTipoPessoa.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        groupRadio.add(radioPF);
        radioPF.setText("Pessoa Física");
        radioPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPFActionPerformed(evt);
            }
        });

        groupRadio.add(radioPJ);
        radioPJ.setText("Pessoa Jurídica");
        radioPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPJActionPerformed(evt);
            }
        });

        jButton1.setText("SALVAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Pesquisar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        frameDadosComuns.setTitle("Dados Comuns");
        frameDadosComuns.setVisible(true);

        lblNome.setText("Nome:");

        lblTelefone.setText("Telefone:");

        lblEndereco.setText("Endereço:");

        javax.swing.GroupLayout frameDadosComunsLayout = new javax.swing.GroupLayout(frameDadosComuns.getContentPane());
        frameDadosComuns.getContentPane().setLayout(frameDadosComunsLayout);
        frameDadosComunsLayout.setHorizontalGroup(
            frameDadosComunsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(frameDadosComunsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(frameDadosComunsLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(frameDadosComunsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblTelefone)
                        .addComponent(lblEndereco)
                        .addComponent(lblNome))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(frameDadosComunsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtEndereco)
                        .addComponent(txtTelefone)
                        .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        frameDadosComunsLayout.setVerticalGroup(
            frameDadosComunsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 93, Short.MAX_VALUE)
            .addGroup(frameDadosComunsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(frameDadosComunsLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(frameDadosComunsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblNome)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(frameDadosComunsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTelefone)
                        .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(frameDadosComunsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEndereco)
                        .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        frameDadosEspecificos.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        frameDadosEspecificos.setTitle("Dados Específicos");
        frameDadosEspecificos.setVisible(true);

        lblRGIE.setText("RG:");

        lblCpfCnpj.setText("CPF:");

        javax.swing.GroupLayout frameDadosEspecificosLayout = new javax.swing.GroupLayout(frameDadosEspecificos.getContentPane());
        frameDadosEspecificos.getContentPane().setLayout(frameDadosEspecificosLayout);
        frameDadosEspecificosLayout.setHorizontalGroup(
            frameDadosEspecificosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(frameDadosEspecificosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(frameDadosEspecificosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(frameDadosEspecificosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblRGIE)
                        .addComponent(lblCpfCnpj))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(frameDadosEspecificosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtRGIE, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                        .addComponent(txtCpfCnpj, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        frameDadosEspecificosLayout.setVerticalGroup(
            frameDadosEspecificosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
            .addGroup(frameDadosEspecificosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(frameDadosEspecificosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(frameDadosEspecificosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblRGIE)
                        .addComponent(txtRGIE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(frameDadosEspecificosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCpfCnpj)
                        .addComponent(txtCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jButton3.setText("Limpar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(85, 85, 85)
                                        .addComponent(lblMensagem))
                                    .addComponent(radioPF))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                                .addComponent(radioPJ))
                            .addComponent(frameDadosComuns)
                            .addComponent(frameDadosEspecificos)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTipoPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addComponent(lblMensagem)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioPF)
                    .addComponent(radioPJ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(frameDadosComuns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(frameDadosEspecificos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPFActionPerformed
        lblTipoPessoa.setText(radioPF.getText().toUpperCase());  
        verificarCamposPessoa(true);
    }//GEN-LAST:event_radioPFActionPerformed

    private void radioPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPJActionPerformed
        lblTipoPessoa.setText(radioPJ.getText().toUpperCase());
        verificarCamposPessoa(false);
    }//GEN-LAST:event_radioPJActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (!radioPF.isSelected() && !radioPJ.isSelected()) {
            alertMessage(this, "Selecione um tipo de pessoa e preencha os campos para cadastrar!", "Atenção!");
            return;
        } else if (radioPF.isSelected()) {
            pessoa = new PessoaFisica(txtNome.getText(), txtTelefone.getText(), txtEndereco.getText(), txtRGIE.getText(), txtCpfCnpj.getText());
        } else {
            pessoa = new PessoaJuridica(txtNome.getText(), txtTelefone.getText(), txtEndereco.getText(), txtRGIE.getText(), txtCpfCnpj.getText());
        }
        
        if(conttroller.cadastrar(pessoa, posicao)){
            successMessage(this, "Cadastro efetuado com sucesso!", "OK!");
            clear();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Pesquisa p = new Pesquisa(this, this.conttroller);
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        clear();
    }//GEN-LAST:event_jButton3ActionPerformed

    public void errorMessage(javax.swing.JFrame tela, String msg, String titulo){
        JOptionPane.showMessageDialog(tela,
        msg, titulo, JOptionPane.ERROR_MESSAGE);
    }
    
    public void alertMessage(javax.swing.JFrame tela, String msg, String titulo){
        JOptionPane.showMessageDialog(tela,
        msg, titulo, JOptionPane.WARNING_MESSAGE);
    }
    
    public void successMessage(javax.swing.JFrame tela, String msg, String titulo){
        JOptionPane.showMessageDialog(tela,
        msg, titulo, JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void verificarCamposPessoa(Boolean habilita) {
        if(habilita){
            lblRGIE.setText("RG:");
            lblCpfCnpj.setText("CPF:");
        }else{
            lblRGIE.setText("IE:");
            lblCpfCnpj.setText("CNPJ:");
        }
        frameDadosEspecificos.setVisible(true);
    }
    
    public CadastroPessoa getConttroller() {
        return conttroller;
    }
    
    public void clear(){
        txtNome.setText("");
        txtTelefone.setText("");
        txtEndereco.setText("");
        txtRGIE.setText("");
        txtCpfCnpj.setText("");
        groupRadio.clearSelection();
        radioPJ.setSelected(false);
        lblTipoPessoa.setText("");
        frameDadosEspecificos.setVisible(false);
    }
    
    public void alterar(Pessoa pessoa){
        txtNome.setText(pessoa.getNome());
        txtTelefone.setText(pessoa.getTelefone());
        txtEndereco.setText(pessoa.getEndereco());
        if (pessoa instanceof PessoaFisica) {
            txtRGIE.setText(((PessoaFisica) pessoa).getRG());
            txtCpfCnpj.setText(((PessoaFisica) pessoa).getCPF());
            lblTipoPessoa.setText(radioPF.getText().toUpperCase());  
            radioPF.setSelected(true);
            radioPJ.setSelected(false);
        }else{
            txtRGIE.setText(((PessoaJuridica) pessoa).getIE());
            txtCpfCnpj.setText(((PessoaJuridica) pessoa).getCNPJ());
            lblTipoPessoa.setText(radioPJ.getText().toUpperCase());  
            radioPF.setSelected(false);
            radioPJ.setSelected(true);
        }
        this.posicao = conttroller.getIndex(pessoa);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cadastro app = new Cadastro();
                app.setVisible(true);
                app.frameDadosEspecificos.setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame frameDadosComuns;
    private javax.swing.JInternalFrame frameDadosEspecificos;
    private javax.swing.ButtonGroup groupRadio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCpfCnpj;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblRGIE;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTipoPessoa;
    private javax.swing.JRadioButton radioPF;
    private javax.swing.JRadioButton radioPJ;
    private javax.swing.JTextField txtCpfCnpj;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRGIE;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
